<?php


return[
    'edit.tab1'=>'System parameters edition',
    'edit.tab2'=>'System actions',
    'success'=>'System parameters successfully modified.',
    'error'=>'There was an error when modifying system parameters.',
    'increment.success'=>'State machine was incremented successfully.',
    'increment.error'=>'There was an error changing the state.',
    'state.actual'=>'Actual State',
    'state.next'=>'Next State',
    'state.go'=>'Go',
    'state.0.title'=>'Inscriptions opened',
    'state.1.title'=>'First Inscriptions computed',
    'state.2.title'=>'Final inscriptions and opened enrollments',
    'state.3.title'=>'Enrollments Closed. First Semester Starts',
    'state.4.title'=>'Opened First Semester Minutes',
    'state.5.title'=>'First Semester Minutes Closed. Second Semester Starts',
    'state.6.title'=>'Opened Second Semester Minutes',
    'state.7.title'=>'Course closed',
    'state.0.body'=>'-<strong>Students</strong> can apply now for different Schools.',
    'state.1.body'=>'-First inscriptions list computed.<br>-<strong>Students</strong> can no longer apply.<br>-<strong>Students</strong> can now accept or decline their offers.',
    'state.2.body'=>'-Second and final inscriptions list computed.<br>-Subject Instances and Groups are autogenerated.<br>-New Students are autogenerated based on accepted inscriptions.<br>-<strong>Students</strong> can enroll Subjects now.<br>-<strong>Management PDIs</strong> cannot modify Subjects, Degrees or Departments anymore.',
    'state.3.body'=>'-<strong>Students</strong> can no longer enroll asignments.<br>-<strong>Management PDIs</strong> can assign the rooms and time for the groups.',
    'state.4.body'=>'-Minutes are autogenerated from Control Checks of Subjects from the first semester.<br>-<strong>Lecturers</strong> can modify Minutes of subjects from the first semester now.',
    'state.5.body'=>'-<strong>Lecturers</strong> cannot change Minutes anymore.',
    'state.6.body'=>'-Minutes are autogenerated from Control Checks of Subjects from the second semester and annuals.<br>-<strong>Lecturers</strong> can modify Minutes of subjects from the second semester and annuals now.\'',
    'state.7.body'=>'-<strong>Lecturers</strong> cannot change Minutes anymore.<br>-<strong>Management PDIs</strong> can modify subjects, departments and degrees now.',

];